import { TimeCard } from "./TimeCard";
import { OrderManager } from "./OrderManager";

const manager = new OrderManager();
const timeCard = new TimeCard();
console.log(true);
manager.AddOrder(1,1,2);
manager.orderTable.at(-1)?.Additem();
manager.orderTable.at(-1)?.Additem();
manager.orderTable.at(-1)?.order[0].AddFlag(2);
manager.orderTable.at(-1)?.order[1].AddFlag(1);
manager.orderTable.at(-1)?.order[1].AddFlag(4);
manager.AddOrder(2,2,1);
manager.orderTable.at(-1)?.Additem();
manager.orderTable.at(-1)?.Additem();
manager.orderTable.at(-1)?.order[0].AddFlag(4);
manager.orderTable.at(-1)?.order[0].AddFlag(8);
manager.orderTable.at(-1)?.order[1].AddFlag(4);
manager.AddOrder(3,2,1);
manager.orderTable.at(-1)?.Additem();
manager.orderTable.at(-1)?.Additem();
manager.orderTable.at(-1)?.Additem();
manager.orderTable.at(-1)?.order[0].AddFlag(2);
manager.orderTable.at(-1)?.order[1].AddFlag(4);
manager.orderTable.at(-1)?.order[2].AddFlag(1);
manager.WriteOrder();
manager.ClearRequestCheck();
console.log(manager.orderTable);